version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -lc "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db-data:
