default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  pool: 10

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "patients_development") %>

test:
  <<: *default
  database: patients_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "patients_production") %>
